# Generated by Django 2.2.6 on 2020-01-15 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0003_auto_20200115_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(default='def.jpg', upload_to=''),
        ),
    ]
