# Generated by Django 2.2.6 on 2019-11-27 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20191120_1614'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=205)),
                ('document', models.FileField(upload_to='document/')),
                ('upload_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
