# Generated by Django 2.2.6 on 2019-11-06 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='products',
            table='products_custom_products',
        ),
    ]
