# Generated by Django 2.2.6 on 2019-11-07 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20191106_1723'),
    ]

    operations = [
        migrations.CreateModel(
            name='buyers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('productid', models.IntegerField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('price', models.FloatField()),
                ('warranty', models.IntegerField()),
            ],
            options={
                'db_table': 'products_buyers_products',
            },
        ),
    ]
