# Generated by Django 2.2.6 on 2019-11-20 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_buyers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyers',
            name='productid',
            field=models.IntegerField(),
        ),
    ]
